name: Solaris CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-on-solaris:
    name: Build & Archive on Solaris
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build project inside Solaris VM
        uses: vmactions/solaris-vm@v1.1.1
        with:
          release: "11.4-gcc"
          usesh: true
          copyback: false
          prepare: |
            uname -a
          run: |
            ./bootstrap-lts-jdk.sh 21

