name: Solaris CI - OpenJDK 21

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-on-solaris:
    name: Build & Archive on Solaris
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build project inside Solaris VM
        uses: vmactions/solaris-vm@v1.1.1
        with:
          release: "11.4-gcc"
          usesh: true
          copyback: false
          prepare: |
            uname -a
          run: |
            #curl -o openjdk-20-bootstrap_SunOS-i386_bin.tar.xz --progress-bar -L https://github.com/psumbera/solaris-openjdk/releases/download/openjdk20-i386-bootstrap/openjdk-20-bootstrap_SunOS-i386_bin.tar.xz
            #gtar xf openjdk-20-bootstrap_SunOS-i386_bin.tar.xz
            #BOOT_JDK=$(pwd)/jdk-20-bootstrap bash jdk-21.sh
            ./archives.sh
            echo test > archives/openjdk-21-SunOS-i386_bin.tar.xz
            mkdir -p /workspace/archives
            mv archives/* /workspace/archives/
            ls -l /workspace/archives/

      - name: Upload Solaris build artifact
        uses: actions/upload-artifact@v4
        with:
          name: openjdk-21-latest_SunOS-i386_bin
          path: archives/*
          run: |
            pwd
            ls
